### PR TITLE
Add Additional Commands And Bump pdfbox version

### PR DESCRIPTION
**Pull request by carlswann**
Add three new commands 
`copy-fields`
`rename-fields`
`translate-fields`

Also bump the version of pdfbox as to include the latest bug fixes

### CODE REVIEW

**Comment by AckerApple** [comment]
Looking good here. Please update README.md and then I will merge.

**Comment by carlswann** [comment]
@AckerApple Updated!

**Comment by AckerApple** [comment]
You are scheduled to be built and published sometime between now and this Saturday by 1pm EST.

Thank you kindly for your contributions. I am very pleased to see this package being updated as I invested a lot of time quite some time ago.

**Comment by AckerApple** [comment]
This work makes me really happy.

**Comment by AckerApple** [comment]
Your code has been published as v1.3.0

**Pull request merged**
